instruct:
  # @hidden
  image: icr.io/ppc64le-oss/vllm-ppc64le:0.18.0
  model: "ibm-granite/granite-3.3-8b-instruct"
  # @description API key for vLLM instruct service authentication. If empty, authentication is disabled. Provide a key to enable authentication.
  apiKey: ""
