name: Services Unit Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'services/**'
      - '.github/workflows/spyre-rag-unit-tests.yml'

jobs:
  test:
    runs-on: ubuntu-24.04-ppc64le
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python 3.12
        uses: IBM/setup-python-pz@291287e36d7c893a50c857d8bc014d67edd58ada
        with:
          python-version: '3.12'

      
      - name: Install digitize test dependencies
        run: |
          pip install -r requirements-test.txt \
          --extra-index-url https://wheels.developerfirst.ibm.com/ppc64le/linux \
          --prefer-binary
        working-directory: services/digitize
      
      - name: Run digitize service tests
        run: |
          pytest tests/ -v
        working-directory: services/digitize
      
      - name: Install chatbot test dependencies
        run: |
          pip install -r requirements-test.txt \
          --extra-index-url https://wheels.developerfirst.ibm.com/ppc64le/linux \
          --prefer-binary
        working-directory: services/chatbot
      
      - name: Run chatbot service tests
        run: |
          pytest tests/ -v
        working-directory: services/chatbot

